### PR TITLE
test: Add e2e tests with playwright for website

### PR DESCRIPTION
**Pull request by rubickecho**
Add e2e tests with playwright for website `https://qwerty.kaiyi.cool`

Include the following features:

* Homepage view
* Switch theme
* Practice list
* Dictionary Management
  * Switch language
  * Switch category
  * Switch dictionary
  * Switch dictionary chapter
* English practice
  * Correct input
  * Wrong input
  * Chapter completed
  * Practice statistical data

And, add e2e github action config, `/workflows/e2e.yml`, it works fine in my repository.
But, I am unsure of the best way to integrate this job into the entire project's release workflow.

**CI job result**
aa
bb

### CODE REVIEW

**Comment by rubickecho** [comment]
I plan to keep updating in the future. add `TestId` to certain crucial elements for the convenience of testing.

**Comment by RealKai42** [comment]
This pr is incredible important to our project, I will review it this weekend
With proper test, we can keep the experience quality while deliver new features ❤️

**Comment by RealKai42** [comment]
🤔 我会好奇，测试框架选型 Playwright 有什么考虑么？
why not Cypress or Selenium

**Comment by rubickecho** [comment]
最大的原因应该是我个人用 playwright 更顺手，它的 API 更容易理解，也可以参考这篇文章
https://www.testim.io/blog/puppeteer-selenium-playwright-cypress-how-to-choose/

**Review by RealKai42 — APPROVED** [review]

**Comment by RealKai42** [comment]
抱歉因为过年耽误了 merge
再次感谢您的贡献 ❤️

**Pull request merged**
